- name: Create IAM OIDC Provider
  hosts: localhost
  vars: 
    REGION: "{{ lookup('ansible.builtin.env','REGION') }}"
    AWS_ACCOUNT_ID: "{{ lookup('ansible.builtin.env','AWS_ACCOUNT_ID') }}"
    CLUSTER_NAME: "{{ lookup('ansible.builtin.env','CLUSTER_NAME') }}"
    
  tasks:
  - name: Download  AWS LB Controller IAM Policy
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.4.5/docs/install/iam_policy.json"
      dest: ./iam_policy.json

  - name: Create IAM Role for AWSLoadBalancerControllerIAMPolicy (Unexpected failure during module execution)
    command: "aws iam create-policy
      --policy-name AWSLoadBalancerControllerIAMPolicy
      --policy-document file://iam_policy.json"
    ignore_errors: yes
      #community.aws.iam_managed_policy:
      #policy_name: "AWSLoadBalancerControllerIAMPolicy"
      #policy: "{{ lookup('file', 'iam_policy.json') }}"
      #state: present

  - name: Create IAM Role & Service Account for AWS LB Controller
    command: "eksctl create iamserviceaccount
  --cluster {{ CLUSTER_NAME }}
--namespace kube-system
--name aws-load-balancer-controller
--attach-policy-arn arn:aws:iam::{{ AWS_ACCOUNT_ID }}:policy/AWSLoadBalancerControllerIAMPolicy
--override-existing-serviceaccounts
--region {{ REGION }}
--approve"

  - name: Update Kubeconfig
    command: "aws eks update-kubeconfig --region {{ REGION }} --name {{ CLUSTER_NAME }}"

  - name: ADD AWS LB Controller Chart repository
    kubernetes.core.helm_repository:
      name: aws
      repo_url: "https://aws.github.io/eks-charts"

  - name: Deploy AWS LB Controller Component
    kubernetes.core.helm:
      name: aws-load-balancer-controller
      chart_ref: aws/aws-load-balancer-controller
      namespace: kube-system
      values:
        clusterName: "{{ CLUSTER_NAME }}"
        region: "{{ REGION }}"
        serviceAccount:
          create: false
          name: aws-load-balancer-controller
