name: EKS CI/CD

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        required: true
        type: string
      CLUSTER_NAME:
        required: true
        type: string
env:
  REGION: ${{ github.event.inputs.region }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  CLUSTER_NAME: ${{ github.event.inputs.CLUSTER_NAME }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Print env
        run: |
          echo $REGION
          echo $AWS_ACCOUNT_ID
          echo $CLUSTER_NAME
      
      - name: kubectl
        run: |
          curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
          apt-get update -y
          apt-get install -y kubectl
          mkdir -p ~/.kube
          cat << EOF > ~/.kube/config
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ERXhOVEU1TURjeU9Wb1hEVE16TURFeE1qRTVNRGN5T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlhsClltUDAvTlBHenpOYnVERHcvZVNVeWF4QnIrdjFJc2VONy9Ick94ZFY3ZHVxcFltdmNCQktmWUxBczNHMGY3TTgKaWtZeTVQYzJ3elBxc3FDeC9lRUkxQWVRMEQyN1hsWjZnaDgvVU5hOVdGNzBySmRkQTRORkJpVmFheEZ3RmlwVApSM05jS2RYV2RQUUNMbnVUOGRSa3d2K2IrdllmZStPamJIUTFvQmhKT1d3ckZOQ0xvb3VUMmxlYVZEdkVyaFg4CkZ5ZFVNMmhmOHYxVnZ2UmwwdHVMRWtmUEtEMjFJWXJaSndCM29DMjZXZnlmUG8xckZEUUN1Z0prMU1QTXNzSUMKOFI5czlFbXNiVjRPejYrS1BDaGp3aVVsZC9lNlFkWHh1NHZ2aU4wZFowODlYejZ0UzI2WmswWXhnRGY1VXFwQwpHSCt4Ui9FZmFrOFcrYkc3QWpVQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKLzErMDFNOTE5WVhvUGx2L0U5K2U5OWRSWm9NQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSzhhQk9iYi9JZERYaTg5L2lYTApLRW8yUEpLdDVYZ0V6OTYwVHRqTHl3aEdLV1ZTYnZSS3RZaUpFTG1LTnNvdCtPZUl2b1JaS2F2aTlBamRYZVVRCjY4UjIzR0JvR05JT0xyYVhPS1JNQjl2Lzd1THVLemQySEszQS84MXcrOTZzUS8yY1pKVTF3cy8wNXM4bmNOeloKQ0I4ckhaMWRwZGdWemMveVhBMDZLTllqSmUvdVMrZUJQUkJFZGRISVcreGVhb0R6TVVlQzhRODAva0ROL3FzZQptVVZhbmRTQXk1N0w5a0I3dXk0WWZCdEplWjdUNE40NDhOMVZjbG0wL0xnWVZBWEpyejdDbnB2Q051N0t2TyswCnUzWkNneGVvb0tCU2VMeFl5ZWZZTXZGZ3NYcFNUTm5zR0V4aENJMCtlaktKTkJnZzZlcC9aRkFmNGJoaFhlREkKcytjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
              server: https://E36FB10D1D24245DB67B5AD4A1E1BCE5.gr7.ap-northeast-2.eks.amazonaws.com
            name: arn:aws:eks:ap-northeast-2:***:cluster/github-actions-2
          contexts:
          - context:
              cluster: arn:aws:eks:ap-northeast-2:***:cluster/github-actions-2
              user: arn:aws:eks:ap-northeast-2:***:cluster/github-actions-2
            name: arn:aws:eks:ap-northeast-2:***:cluster/github-actions-2
          current-context: arn:aws:eks:ap-northeast-2:***:cluster/github-actions-2
          kind: Config
          preferences: {}
          users:
          - name: arn:aws:eks:ap-northeast-2:***:cluster/github-actions-2
            user:
              exec:
                apiVersion: client.authentication.k8s.io/v1beta1
                args:
                - --region
                - ap-northeast-2
                - eks
                - get-token
                - --cluster-name
                - github-actions-2
                command: aws
          EOF
          kubectl patch service nginx-svc -p '{"spec":{"type": "NodePort"}}'
