name: EKS CI/CD

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        required: true
        type: string
      CLUSTER_NAME:
        required: true
        type: string
env:
  REGION: ${{ github.event.inputs.region }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  CLUSTER_NAME: ${{ github.event.inputs.CLUSTER_NAME }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Print env
        run: |
          echo $REGION
          echo $AWS_ACCOUNT_ID
          echo $CLUSTER_NAME
      
      - name: kubectl
        run: |
          curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
          apt-get update -y
          apt-get install -y kubectl
          kubectl patch service nginx-svc -p '{"spec":{"type": "NodePort"}}'
